---
title: "Practica_programada_3"
author: "Ángela Fallas Céspedes"
date: "2023-12-05"
output: html_document
editor_options: 
  chunk_output_type: console
---

Packages
```{r}
library(shiny)
library(ggplot2)
library(shinydashboard)
library(dplyr)
library(readxl)
library(ggplot2)
library(gapminder)
library(readr)
library(plotly)
```

Base de datos
```{r}
datos_spotify <- read.csv2("datos/spotify_2000_2023.csv", header = TRUE)
```

Elegir el año y el género musical para visualizar los datos de las canciones top en Spotify.

```{r}
 ui <- dashboardPage(skin = "purple",
  dashboardHeader(title = "Análisis de Spotify"),
  dashboardSidebar(
    sidebarMenu(
      selectInput(inputId = "year",
               label = "Año",
               choices = unique(datos_spotify$year),
               selected = unique(datos_spotify$year)[4]),
      selectInput(inputId = "top.genre",
                  label = "Género",
                  choices = unique(datos_spotify$top.genre),
                  selected = unique(datos_spotify$top.genre)[3]),      
                  )
),
  dashboardBody(
    plotOutput("grafico_1")
      
    )
)

server <- function(input, output, session) {

    output$grafico_1 <- renderPlot({
    ggplot(data = datos_spotify) +
      geom_point(mapping = aes_string(x = "bpm", y = "popularity"))
  })

}
shinyApp(ui, server)

```



```{r}
ui <- dashboardPage(
  skin = "purple",
  dashboardHeader(title = "Análisis de Spotify"),
  dashboardSidebar(
    sidebarMenu(
      selectInput(inputId = "year",
                  label = "Año",
                  choices = unique(datos_spotify$year),
                  selected = unique(datos_spotify$year)[4]),
      selectInput(inputId = "top.genre",
                  label = "Género",
                  choices = unique(datos_spotify$top.genre),
                  selected = unique(datos_spotify$top.genre)[3])
    )
  ),
  dashboardBody(
    plotOutput("grafico_1")
  )
)

server <- function(input, output, session) {
  output$grafico_1 <- renderPlot({
    ggplot(data = datos_spotify) +
      geom_point(mapping = aes_string(x = "bpm", y = "popularity"))
  })
}

shinyApp(ui, server)


```


```{r}

```

```{r}

```

